server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:tackDB
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  mail:
    host: pop.gmail.com
    port: 587
    username: springboottestemailsubmiter@gmail.com
    password: juypbtdbwvbwtvsi
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  thymeleaf:
    check-template: true
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: 53cr3t
        instance:
          management-base-url: http://localhost:8080
  application:
    name: TacoBel

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

custom:
  url: localhost:8080/confirm?toke=
