server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:deliveryDB
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: 53cr3t
        instance:
          management-base-url: http://localhost:8081
  application:
    name: TacoBel

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
