server:
  port: 8082

custom:
  email:
    host: smtp.gmail.com
    mailbox: INBOX
    username: springboottestemailsubmiter@gmail.com
    password: juypbtdbwvbwtvsi
    poll-rate: 10000

    api:
      url: http://localhost:8080/orders/fromEmail

spring:
  main:
    web-application-type: none
